### ISSUE TITLE
Error loading file

### ISSUE THREAD

**Issue by TroubleMakerBen** [Microsoft/mobile-center-sdk-react-native#32] opened 2017-05-08 17:04 UTC
On our iOS SDK GH, @pvinis [has created an issue](https://github.com/Microsoft/mobile-center-sdk-ios/issues/535) which belongs here.

> I added this sdk to a react native app, by just adding the npm packages and then in cocoapods, like the recommended way says. I call the generate crash on the native part of the application, and it crashes correctly. Then next time it opens, i get an error like `[MobileCenterCrashes] ERROR: -[MSWrapperExceptionManager loadWrapperExceptionDataWithUUIDString:]/179 Error loading file /var/mobile/Containers/Data/Application/C6EEA96E-122D-4A1F-B78C-CE8C506CFD24/Documents/wrapper_exceptions/A2FCB855-6C78-499A-A55B-85F7C438CC51.ms: The file “A2FCB855-6C78-499A-A55B-85F7C438CC51.ms” couldn’t be opened because there is no such file.`
> What is the problem? It is a bug?

Let's look into this and see what the problem is.

**Comment by jeveloper** [comment] 2017-05-23 17:07
Why was this closed?

The latest sdk hasnt been updated to 0.9 , come on microsoft
crash files arent sent

[MSWrapperExceptionManager loadWrapperExceptionDataWithUUIDString:]/179 Error loading file /var/mobile/Containers/Data/Application/BF44BD49-6452-4052-A6AB-3921DEE934A3/Documents/wrapper_exceptions/ED856905-8FCD-47C1-BA47-4E27B38FDFB8.ms: The file “ED856905-8FCD-47C1-BA47-4E27B38FDFB8.ms” couldn’t be opened because there is no such file.

**Comment by jaelim-ms** [comment] 2017-06-02 17:19
The issue has not been closed. The issue is on React Native side so we want to track this here. It only closed on iOS repo.

**Comment by BretJohnson** [comment] 2017-06-15 06:30
@jeveloper @pvinis The RN SDK was updated to version 0.5.0 earlier this week, which uses the latest native SDKs (0.9).
I'm not sure of the original root cause here (SDK version mismatch possibly?) but can you please see if the issue still happens for you guys, with the latest RN SDK. Thx.

**Comment by jeveloper** [comment] 2017-06-18 11:28
thank you 
this should be good now

**Comment by guperrot** [comment] 2017-07-25 01:26
@jeveloper Hi, I am triaging issues and this one seems fixed. Closing it, let me know if closing it is a mistake.

**Closed by guperrot** 2017-07-25 01:26 UTC
